apiVersion : apps/v1
kind : Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name : hello-pod
        image : nigelpoulton/k8sbook:latest
        ports:
        - containerPort: 8081