# test.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Test Kubernetes</title>
    </head>
    <body>
      <h1>Bienvenue sur Nginx dans Kubernetes!</h1>
    </body>
    </html>
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  containers:
  - name: hello-ctr
    image: nginx:latest    
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-html
    configMap:
      name: nginx-content